repos:
- repo: local
  hooks:
    - id: pylint-error-count
      name: pylint-error-count
      entry: bash -c 'touch siva.txt'
      language: system
      types: [python]
      pass_filenames: false
