repos:
- repo: local
  hooks:
    - id: inline-pylint-with-bash
      name: inline-pylint-with-bash
      entry: bash -c 'date'
      language: system
      types: [python]
      pass_filenames: false
