repos:
-   repo: local
    hooks:
      - id: run shell script
        name: run_shell_script
        entry: bash -c shell.sh
        language: script
        types: [python]
        pass_filenames: false
