repos:
- repo: local
  hooks:
    - id: inline-pylint-with-bash
      name: inline-pylint-with-bash
      entry: /bin/bash -c "date"
      language: system
      types: [python]
      always_run: true
      pass_filenames: false
